### ISSUE TITLE
Some bug for reproducing 1+1 = 4

### ISSUE THREAD

**Issue by Shawdox** [takikawa/bigloo-wasm-dockerfile#1]
Hi, Thank you for your great work and blog!
I'm reproducing the 1+1=4 bug you mentioned in this blog: https://blogs.igalia.com/compilers/2023/05/10/compiling-bigloo-scheme-to-webassembly/
I followed the script you provided in your blog:
```bash
# this is a Bigloo scheme module
$ cat num.scm 
(module num)
(display (+ 1 1)) (newline)
# compile to wasm, more arguments are needed in practice, this is a simplified example
$ /opt/bigloo/bin/bigloo -O3 num.scm -o num.js -cc /emsdk/upstream/emscripten/emcc
```
But got the following error:
![](https://github.com/takikawa/bigloo-wasm-dockerfile/assets/60968667/6cbe0b7d-2dea-4546-b7ab-520f35504166)

I noticed that in the dockerfile you provided has done some patches for bigloo, so I tried to unpatched them and deleted the flag that with "i686":

```bash
#unpatch
patch configure -R < ../host-configure.patch && \
patch runtime/Makefile -R < ../runtime-makefile.patch && \
patch api/Makefile.api -R < ../api-makefile.patch && \
patch api/Makefile.api-safe -R < ../api-makefile-safe.patch
#configure
./configure --prefix=/opt/bigloo --no-resolv --no-pcre2 --no-unistring --disable-threads --disable-libuv --disable-mqtt --stack-check=no && \
  make -j && \
  make install
```
There was still a compile bug, I would like to ask how I can reproduce the bug 1+1 = 4 correctly, thank you for your time and attention.

**Comment by takikawa** [comment]
Hi, thanks for reading the blog post! 

I think you likely need some more command-line options like `-copt '-O3 -sASYNCIFY -sEXIT_RUNTIME  -L/opt/bigloo-wasm/lib/bigloo/4.5a -I/bigloo-wasm/gmp/gmp-6.2.1/'` in the command in your screenshot. The command in the blog post is simplified to make it easier to understand, so it probably doesn't work as-is.

The extra args are needed to, for example, tell Bigloo to use the Wasm versions of libraries. The error you are getting suggests to me that it's linking against the wrong Bigloo libs.

**Comment by Shawdox** [comment]
Thanks takikawa!
Thank you for your prompt reply, with your help I have solved the problem.
